### ISSUE TITLE
Dump chip

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [nopnop2002/Raspberry-W25Q64#13]
Hello,

I would like to dump the entire flash to a file. How do i do it?

**Comment by nopnop2002** [comment]
Use this.

// Read data from memory
uint16_t W25Q64_read(uint32_t addr,uint8_t *buf,uint16_t n);

// First read data from memory
uint16_t W25Q64_fastread(uint32_t addr,uint8_t *buf,uint16_t n);
